name: "publish"

# This will trigger the action on each push to the `release` branch.
on: [push]

jobs:
  publish-tauri:
    permissions:
      contents: write
      deployments: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
        # platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: pnpm install # change this to npm or pnpm depending on which one you use

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false

      - name: List src-tauri/target/release/bundle
        run: ls -lt src-tauri/target/release/bundle

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: tauri-test
          path: src-tauri/target/release/bundle/dmg/

      - name: Echo artifact id
        run: echo 'Artifact Id ${{steps.artifact-upload-step.outputs.artifact-id}}'

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: preview
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          description: "Deploy to preview environment"
          environment: preview

      - name: Upload to s3
        uses: shallwefootball/s3-upload-action@master
        id: s3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'src-tauri/target/release/bundle/dmg/'

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # s3://tauri-test.westcoastcode.com/index.html
          # https://west-coast-code.s3.ca-central-1.amazonaws.com/tauri-test/
          # https://s3.us-west-2.amazonaws.com/tauri-test.westcoastcode.com/index.html
          target_url: https://s3.us-west-2.amazonaws.com/tauri-test.westcoastcode.com/tauri-test/${{steps.S3.outputs.object_key}}
          state: 'success'
          deployment_id: ${{ steps.preview.outputs.deployment_id }}
  
  